spring:
  application:
    name: practice

  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: batool
    driver-class-name: org.postgresql.Driver


  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
